// lib/categories.js
// Central source of truth for all categories and subcategories
// Import this wherever you need category data

export const CATEGORIES = [
  {
    id: "grocery",
    label: "Grocery",
    emoji: "🛒",
    color: "#22c55e",
    href: "/grocery",
    priceOptional: false,
    subcategories: [
      { id: "dairy", label: "Dairy Products" },
      { id: "student-daily", label: "Student Daily Use" },
      { id: "chocolates", label: "Chocolates" },
      { id: "dry-fruits", label: "Dry Fruits & Nuts" },
      { id: "snacks-namkeen", label: "Snacks & Namkeen" },
      { id: "kitchen", label: "Kitchen Ingredients" },
      { id: "instant-food", label: "Instant Food" },
      { id: "energy-drinks", label: "Energy Drinks" },
      { id: "beverages", label: "Beverages" },
      { id: "meat-fish", label: "Meat & Fish" },
      { id: "frozen-packaged", label: "Frozen & Packaged Food" },
      { id: "seasonal-fruits", label: "Seasonal Fruits" },
      { id: "green-vegetables", label: "Green Vegetables" },
      { id: "cut-fruits", label: "Cut Fruits" },
      { id: "fruits-vegetables", label: "Fruits & Vegetables" },
      { id: "sprouts", label: "Sprouts" },
      { id: "coconut-water", label: "Coconut Water" },
      { id: "healthy-fruits", label: "Healthy Fruits" },
    ],
  },
  {
    id: "food",
    label: "Food",
    emoji: "🍔",
    color: "#f97316",
    href: "/food",
    priceOptional: false,
    subcategories: [
      { id: "fast-food", label: "Fast Food" },
      { id: "veg-food", label: "Veg Food" },
      { id: "non-veg-food", label: "Non Veg Food" },
      { id: "sweets-desserts", label: "Sweets & Desserts" },
      { id: "bakery", label: "Bakery Items" },
      { id: "ice-cream", label: "Ice Cream" },
      { id: "tiffin", label: "Tiffin Services" },
    ],
  },
  {
    id: "juices-shakes",
    label: "Juices & Shakes",
    emoji: "🥤",
    color: "#eab308",
    href: "/juices-shakes",
    priceOptional: false,
    subcategories: [
      { id: "fresh-juice", label: "Fresh Juice" },
      { id: "shakes", label: "Shakes" },
      { id: "tea-coffee", label: "Tea & Coffee" },
      { id: "cold-drinks", label: "Cold Drinks" },
      { id: "milkshakes", label: "Milkshakes" },
      { id: "mocktails", label: "Mocktails" },
    ],
  },
  {
    id: "stationery",
    label: "Stationery",
    emoji: "✏️",
    color: "#3b82f6",
    href: "/stationery",
    priceOptional: false,
    subcategories: [
      { id: "books-notebooks", label: "Books & Notebooks" },
      { id: "calculators", label: "Calculators" },
      { id: "drawing-materials", label: "Drawing Materials" },
      { id: "pens", label: "Pens (All Types)" },
      { id: "files-folders", label: "Files & Folders" },
      { id: "btech-polytechnic", label: "BTech & Polytechnic Materials" },
      { id: "xerox-printout", label: "Xerox / Printout" },
      { id: "jamia-school", label: "Jamia School Material" },
      { id: "other-stationery", label: "Other Stationery" },
    ],
  },
  {
    id: "assignment",
    label: "Assignment Services",
    emoji: "📝",
    color: "#8b5cf6",
    href: "/others",
    priceOptional: true,
    subcategories: [
      { id: "ignou-assignment", label: "IGNOU Assignment Work" },
      { id: "handwritten", label: "Handwritten Assignments" },
      { id: "typed", label: "Typed Assignments" },
      { id: "project-work", label: "Project Work" },
      { id: "ppt", label: "Presentation (PPT) Making" },
      { id: "engineering-drawing", label: "Engineering Drawing" },
      { id: "polytechnic-drawing", label: "Polytechnic Drawing" },
      { id: "thesis", label: "Thesis Help" },
      { id: "school-assignment", label: "School Assignment" },
      { id: "college-assignment", label: "College Assignment" },
      { id: "drawing-work", label: "Drawing Work" },
      { id: "important-questions", label: "Important Questions Solving" },
    ],
  },
  {
    id: "tuition",
    label: "Tuition Services",
    emoji: "🎓",
    color: "#06b6d4",
    href: "/others",
    priceOptional: true,
    subcategories: [
      { id: "school-tuition", label: "School Tuition Available" },
      { id: "college-tuition", label: "College Tuition Available" },
      { id: "home-tuition", label: "Home Tuition Available" },
      { id: "entrance-exam", label: "Entrance Exam Preparation" },
      { id: "tutor-available", label: "Tutor Available" },
      { id: "ignou-help", label: "IGNOU Help" },
      { id: "exam-form", label: "Exam Form Filling" },
      { id: "online-form", label: "Online Form Filling Service" },
    ],
  },
  {
    id: "earn-rent",
    label: "Student Earn & Rent Hub",
    emoji: "🏠",
    color: "#ec4899",
    href: "/others",
    priceOptional: true,
    subcategories: [
      { id: "calculators-rent", label: "Calculators on Rent" },
      { id: "pg-rooms", label: "PG / Rooms on Rent" },
      { id: "electronics-rent", label: "Electronics on Rent" },
      { id: "room-essentials", label: "Room Essentials on Rent" },
      { id: "travel-transport", label: "Travel & Transport on Rent" },
      { id: "daily-items-rent", label: "Daily Use Items on Rent" },
      { id: "money-rent", label: "Money on Rent" },
    ],
  },
  {
    id: "others",
    label: "Others",
    emoji: "⚡",
    color: "#17d492",
    href: "/others",
    priceOptional: true,
    subcategories: [
      { id: "ironing", label: "Clothes Ironing" },
      { id: "laundry", label: "Laundry Service" },
      { id: "dry-cleaning", label: "Dry Cleaning" },
      { id: "resume", label: "Resume / CV Making" },
      { id: "recharge", label: "Mobile Recharge & Bill Payment" },
      { id: "laptop-repair", label: "Laptop / Mobile Repair" },
      { id: "packing-shifting", label: "Packing & Shifting Help" },
      { id: "printout-scan", label: "Printout / Scan Service" },
      { id: "id-card", label: "ID Card / Document Help" },
      { id: "shoes-bags", label: "Shoes & Bags" },
      { id: "utensils", label: "Utensils Services" },
      { id: "clothes", label: "Clothes Section" },
      { id: "chemist", label: "Chemist & Cosmetics" },
      { id: "pyq", label: "PYQ Section" },
    ],
  },
];

export const CATEGORY_MAP = CATEGORIES.reduce((acc, cat) => {
  acc[cat.id] = cat;
  return acc;
}, {});
